add_test( [==[书架：refresh 加载全部条目]==] /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/bin/openread-vm-tests [==[--test-case=书架：refresh 加载全部条目]==])
set_tests_properties( [==[书架：refresh 加载全部条目]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/tests LABELS)
add_test( [==[书架：remove 后列表自动刷新]==] /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/bin/openread-vm-tests [==[--test-case=书架：remove 后列表自动刷新]==])
set_tests_properties( [==[书架：remove 后列表自动刷新]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/tests LABELS)
add_test( [==[书架：add 后列表自动刷新，重复 add 不增加]==] /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/bin/openread-vm-tests [==[--test-case=书架：add 后列表自动刷新，重复 add 不增加]==])
set_tests_properties( [==[书架：add 后列表自动刷新，重复 add 不增加]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/tests LABELS)
add_test( [==[书架：backend 抛异常时 last_error 被填充]==] /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/bin/openread-vm-tests [==[--test-case=书架：backend 抛异常时 last_error 被填充]==])
set_tests_properties( [==[书架：backend 抛异常时 last_error 被填充]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/tests LABELS)
add_test( [==[ReaderViewModel: load_catalog 设置 chapters 和 chapter_count]==] /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/bin/openread-vm-tests [==[--test-case=ReaderViewModel: load_catalog 设置 chapters 和 chapter_count]==])
set_tests_properties( [==[ReaderViewModel: load_catalog 设置 chapters 和 chapter_count]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/tests LABELS)
add_test( [==[ReaderViewModel: open_chapter 设置 content/index/title/percent]==] /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/bin/openread-vm-tests [==[--test-case=ReaderViewModel: open_chapter 设置 content/index/title/percent]==])
set_tests_properties( [==[ReaderViewModel: open_chapter 设置 content/index/title/percent]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/tests LABELS)
add_test( [==[ReaderViewModel: save_progress 传递正确数据到后端]==] /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/bin/openread-vm-tests [==[--test-case=ReaderViewModel: save_progress 传递正确数据到后端]==])
set_tests_properties( [==[ReaderViewModel: save_progress 传递正确数据到后端]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/tests LABELS)
add_test( [==[ReaderViewModel: 空目录时 open_chapter 不崩溃]==] /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/bin/openread-vm-tests [==[--test-case=ReaderViewModel: 空目录时 open_chapter 不崩溃]==])
set_tests_properties( [==[ReaderViewModel: 空目录时 open_chapter 不崩溃]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/tests LABELS)
add_test( [==[端到端：用户输入 → 搜索 → 结果数自动显示到控件]==] /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/bin/openread-vm-tests [==[--test-case=端到端：用户输入 → 搜索 → 结果数自动显示到控件]==])
set_tests_properties( [==[端到端：用户输入 → 搜索 → 结果数自动显示到控件]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/tests LABELS)
add_test( [==[端到端：VM→View 反向同步——改 Property 自动刷新控件文本]==] /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/bin/openread-vm-tests [==[--test-case=端到端：VM→View 反向同步——改 Property 自动刷新控件文本]==])
set_tests_properties( [==[端到端：VM→View 反向同步——改 Property 自动刷新控件文本]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/tests LABELS)
add_test( [==[流式搜索：多个源逐批 append，found_count 实时递增]==] /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/bin/openread-vm-tests [==[--test-case=流式搜索：多个源逐批 append，found_count 实时递增]==])
set_tests_properties( [==[流式搜索：多个源逐批 append，found_count 实时递增]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/tests LABELS)
add_test( [==[流式搜索：再次搜索先清空旧结果]==] /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/bin/openread-vm-tests [==[--test-case=流式搜索：再次搜索先清空旧结果]==])
set_tests_properties( [==[流式搜索：再次搜索先清空旧结果]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/tests LABELS)
add_test( [==[流式搜索：空 emit 不污染列表，总数为 0]==] /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/bin/openread-vm-tests [==[--test-case=流式搜索：空 emit 不污染列表，总数为 0]==])
set_tests_properties( [==[流式搜索：空 emit 不污染列表，总数为 0]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/tests LABELS)
add_test( [==[流式搜索：进行中 cancel 后实现停止继续 emit]==] /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/bin/openread-vm-tests [==[--test-case=流式搜索：进行中 cancel 后实现停止继续 emit]==])
set_tests_properties( [==[流式搜索：进行中 cancel 后实现停止继续 emit]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/tests LABELS)
add_test( [==[流式搜索：搜索实现抛异常时 last_error 被填充]==] /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/bin/openread-vm-tests [==[--test-case=流式搜索：搜索实现抛异常时 last_error 被填充]==])
set_tests_properties( [==[流式搜索：搜索实现抛异常时 last_error 被填充]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/tests LABELS)
add_test( [==[SourceViewModel: refresh 设置 sources/stats/count]==] /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/bin/openread-vm-tests [==[--test-case=SourceViewModel: refresh 设置 sources/stats/count]==])
set_tests_properties( [==[SourceViewModel: refresh 设置 sources/stats/count]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/tests LABELS)
add_test( [==[SourceViewModel: load_from_json 自动刷新列表]==] /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/bin/openread-vm-tests [==[--test-case=SourceViewModel: load_from_json 自动刷新列表]==])
set_tests_properties( [==[SourceViewModel: load_from_json 自动刷新列表]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/tests LABELS)
add_test( [==[SourceViewModel: clear_all 清空列表]==] /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/bin/openread-vm-tests [==[--test-case=SourceViewModel: clear_all 清空列表]==])
set_tests_properties( [==[SourceViewModel: clear_all 清空列表]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/tests LABELS)
add_test( [==[SourceViewModel: export_good 返回 JSON]==] /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/bin/openread-vm-tests [==[--test-case=SourceViewModel: export_good 返回 JSON]==])
set_tests_properties( [==[SourceViewModel: export_good 返回 JSON]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/tests LABELS)
add_test( [==[SourceViewModel: validate 设置进度并在完成后刷新]==] /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/bin/openread-vm-tests [==[--test-case=SourceViewModel: validate 设置进度并在完成后刷新]==])
set_tests_properties( [==[SourceViewModel: validate 设置进度并在完成后刷新]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-ci-check/tests LABELS)
set( openread-vm-tests_TESTS [==[书架：refresh 加载全部条目]==] [==[书架：remove 后列表自动刷新]==] [==[书架：add 后列表自动刷新，重复 add 不增加]==] [==[书架：backend 抛异常时 last_error 被填充]==] [==[ReaderViewModel: load_catalog 设置 chapters 和 chapter_count]==] [==[ReaderViewModel: open_chapter 设置 content/index/title/percent]==] [==[ReaderViewModel: save_progress 传递正确数据到后端]==] [==[ReaderViewModel: 空目录时 open_chapter 不崩溃]==] [==[端到端：用户输入 → 搜索 → 结果数自动显示到控件]==] [==[端到端：VM→View 反向同步——改 Property 自动刷新控件文本]==] [==[流式搜索：多个源逐批 append，found_count 实时递增]==] [==[流式搜索：再次搜索先清空旧结果]==] [==[流式搜索：空 emit 不污染列表，总数为 0]==] [==[流式搜索：进行中 cancel 后实现停止继续 emit]==] [==[流式搜索：搜索实现抛异常时 last_error 被填充]==] [==[SourceViewModel: refresh 设置 sources/stats/count]==] [==[SourceViewModel: load_from_json 自动刷新列表]==] [==[SourceViewModel: clear_all 清空列表]==] [==[SourceViewModel: export_good 返回 JSON]==] [==[SourceViewModel: validate 设置进度并在完成后刷新]==])
