add_test( [==[DebugConsole - 输出日志结果与隔离状态]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=DebugConsole - 输出日志结果与隔离状态]==])
set_tests_properties( [==[DebugConsole - 输出日志结果与隔离状态]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[DebugConsole - 错误超时与输入限制]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=DebugConsole - 错误超时与输入限制]==])
set_tests_properties( [==[DebugConsole - 错误超时与输入限制]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[DebugConsole - 输出上限与 UTF8 边界]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=DebugConsole - 输出上限与 UTF8 边界]==])
set_tests_properties( [==[DebugConsole - 输出上限与 UTF8 边界]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[DebugConsole - 异常输出上限与 UTF8 边界]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=DebugConsole - 异常输出上限与 UTF8 边界]==])
set_tests_properties( [==[DebugConsole - 异常输出上限与 UTF8 边界]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SourceDebug - 搜索目录正文及 HTTP 事件]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SourceDebug - 搜索目录正文及 HTTP 事件]==])
set_tests_properties( [==[SourceDebug - 搜索目录正文及 HTTP 事件]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SourceDebug - 空搜索结果报告阶段失败]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SourceDebug - 空搜索结果报告阶段失败]==])
set_tests_properties( [==[SourceDebug - 空搜索结果报告阶段失败]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SourceDebug - 断连后不再发起请求]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SourceDebug - 断连后不再发起请求]==])
set_tests_properties( [==[SourceDebug - 断连后不再发起请求]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SourceDebug - 多项慢规则共享整体时间预算]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SourceDebug - 多项慢规则共享整体时间预算]==])
set_tests_properties( [==[SourceDebug - 多项慢规则共享整体时间预算]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SourceDebug - JS 执行中断连立即取消且不再发起 HTTP]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SourceDebug - JS 执行中断连立即取消且不再发起 HTTP]==])
set_tests_properties( [==[SourceDebug - JS 执行中断连立即取消且不再发起 HTTP]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SourceDebug - JS HTTP 桥接不能吞掉请求上限错误]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SourceDebug - JS HTTP 桥接不能吞掉请求上限错误]==])
set_tests_properties( [==[SourceDebug - JS HTTP 桥接不能吞掉请求上限错误]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SourceDebug - 引擎取消检查清空后可重新使用]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SourceDebug - 引擎取消检查清空后可重新使用]==])
set_tests_properties( [==[SourceDebug - 引擎取消检查清空后可重新使用]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SourceDebug - 指定书源读取取消后恢复原先选择]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SourceDebug - 指定书源读取取消后恢复原先选择]==])
set_tests_properties( [==[SourceDebug - 指定书源读取取消后恢复原先选择]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SourceDebug - RSS 读取取消后移除临时书源并恢复选择]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SourceDebug - RSS 读取取消后移除临时书源并恢复选择]==])
set_tests_properties( [==[SourceDebug - RSS 读取取消后移除临时书源并恢复选择]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SourceDebug - JS HTTP 桥接不能吞掉一次性取消检查异常]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SourceDebug - JS HTTP 桥接不能吞掉一次性取消检查异常]==])
set_tests_properties( [==[SourceDebug - JS HTTP 桥接不能吞掉一次性取消检查异常]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[StartupOptions - 默认值和帮助]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=StartupOptions - 默认值和帮助]==])
set_tests_properties( [==[StartupOptions - 默认值和帮助]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[StartupOptions - 命名参数互不干扰]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=StartupOptions - 命名参数互不干扰]==])
set_tests_properties( [==[StartupOptions - 命名参数互不干扰]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[StartupOptions - 兼容位置参数及混合参数]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=StartupOptions - 兼容位置参数及混合参数]==])
set_tests_properties( [==[StartupOptions - 兼容位置参数及混合参数]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[StartupOptions - 拒绝无效端口及参数]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=StartupOptions - 拒绝无效端口及参数]==])
set_tests_properties( [==[StartupOptions - 拒绝无效端口及参数]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[JsRuntime - 死循环超时后仍可复用]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=JsRuntime - 死循环超时后仍可复用]==])
set_tests_properties( [==[JsRuntime - 死循环超时后仍可复用]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[JsRuntime - 规则超时不会回退原文且错误不污染后续执行]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=JsRuntime - 规则超时不会回退原文且错误不污染后续执行]==])
set_tests_properties( [==[JsRuntime - 规则超时不会回退原文且错误不污染后续执行]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[JsRuntime - 结果转换期间同样受超时约束]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=JsRuntime - 结果转换期间同样受超时约束]==])
set_tests_properties( [==[JsRuntime - 结果转换期间同样受超时约束]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[JsRuntime - 序列化异常被报告和消费且不会回退原文]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=JsRuntime - 序列化异常被报告和消费且不会回退原文]==])
set_tests_properties( [==[JsRuntime - 序列化异常被报告和消费且不会回退原文]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[JsRuntime - 读取序列化函数异常保留原始错误]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=JsRuntime - 读取序列化函数异常保留原始错误]==])
set_tests_properties( [==[JsRuntime - 读取序列化函数异常保留原始错误]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[JsRuntime - 异常格式化再次异常或超时均被消费]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=JsRuntime - 异常格式化再次异常或超时均被消费]==])
set_tests_properties( [==[JsRuntime - 异常格式化再次异常或超时均被消费]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[JsRuntime - 执行前中断不执行脚本且清除回调后可复用]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=JsRuntime - 执行前中断不执行脚本且清除回调后可复用]==])
set_tests_properties( [==[JsRuntime - 执行前中断不执行脚本且清除回调后可复用]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[JsRuntime - 执行中中断不会被脚本捕获吞掉]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=JsRuntime - 执行中中断不会被脚本捕获吞掉]==])
set_tests_properties( [==[JsRuntime - 执行中中断不会被脚本捕获吞掉]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[JsRuntime - 中断回调抛出的异常不会跨越 QuickJS 边界]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=JsRuntime - 中断回调抛出的异常不会跨越 QuickJS 边界]==])
set_tests_properties( [==[JsRuntime - 中断回调抛出的异常不会跨越 QuickJS 边界]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[JsRuntime - 序列化时同样响应中断且错误不污染后续执行]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=JsRuntime - 序列化时同样响应中断且错误不污染后续执行]==])
set_tests_properties( [==[JsRuntime - 序列化时同样响应中断且错误不污染后续执行]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[JsRuntime - 拒绝非正数超时]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=JsRuntime - 拒绝非正数超时]==])
set_tests_properties( [==[JsRuntime - 拒绝非正数超时]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[CssEngine - 基础类型/class/id 选择]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=CssEngine - 基础类型/class/id 选择]==])
set_tests_properties( [==[CssEngine - 基础类型/class/id 选择]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[CssEngine - 组合器]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=CssEngine - 组合器]==])
set_tests_properties( [==[CssEngine - 组合器]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[CssEngine - 属性选择器]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=CssEngine - 属性选择器]==])
set_tests_properties( [==[CssEngine - 属性选择器]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[CssEngine - 伪类]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=CssEngine - 伪类]==])
set_tests_properties( [==[CssEngine - 伪类]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[CssSelector - @CSS: 规则取值]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=CssSelector - @CSS: 规则取值]==])
set_tests_properties( [==[CssSelector - @CSS: 规则取值]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[XPathEngine - 路径与属性]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=XPathEngine - 路径与属性]==])
set_tests_properties( [==[XPathEngine - 路径与属性]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SelectorFactory - 新引擎可创建并工作]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SelectorFactory - 新引擎可创建并工作]==])
set_tests_properties( [==[SelectorFactory - 新引擎可创建并工作]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[JsRuntime - @put/@get 变量表]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=JsRuntime - @put/@get 变量表]==])
set_tests_properties( [==[JsRuntime - @put/@get 变量表]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[JsRuntime - java.ajax 经 HttpFunc 真实回调]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=JsRuntime - java.ajax 经 HttpFunc 真实回调]==])
set_tests_properties( [==[JsRuntime - java.ajax 经 HttpFunc 真实回调]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[applyRuleStatic - @put 写入 + @get 读取]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=applyRuleStatic - @put 写入 + @get 读取]==])
set_tests_properties( [==[applyRuleStatic - @put 写入 + @get 读取]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[DefaultJSoup - CSS 兜底处理复杂选择器]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=DefaultJSoup - CSS 兜底处理复杂选择器]==])
set_tests_properties( [==[DefaultJSoup - CSS 兜底处理复杂选择器]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[applyRuleStatic - && 为合并而非管道]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=applyRuleStatic - && 为合并而非管道]==])
set_tests_properties( [==[applyRuleStatic - && 为合并而非管道]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[applyRuleStatic - 模板内嵌 {{选择器&&选择器}} 多结果 join]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=applyRuleStatic - 模板内嵌 {{选择器&&选择器}} 多结果 join]==])
set_tests_properties( [==[applyRuleStatic - 模板内嵌 {{选择器&&选择器}} 多结果 join]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SourceDatabase - 书源插入和查询]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SourceDatabase - 书源插入和查询]==])
set_tests_properties( [==[SourceDatabase - 书源插入和查询]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SourceDatabase - validity 持久化到数据库]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SourceDatabase - validity 持久化到数据库]==])
set_tests_properties( [==[SourceDatabase - validity 持久化到数据库]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SourceDatabase - removeInvalidSources 删除差和无效]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SourceDatabase - removeInvalidSources 删除差和无效]==])
set_tests_properties( [==[SourceDatabase - removeInvalidSources 删除差和无效]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SourceDatabase - 书架操作]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SourceDatabase - 书架操作]==])
set_tests_properties( [==[SourceDatabase - 书架操作]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SourceDatabase - 目录缓存]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SourceDatabase - 目录缓存]==])
set_tests_properties( [==[SourceDatabase - 目录缓存]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SourceDatabase - 正文缓存]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SourceDatabase - 正文缓存]==])
set_tests_properties( [==[SourceDatabase - 正文缓存]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SourceDatabase - 阅读进度]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SourceDatabase - 阅读进度]==])
set_tests_properties( [==[SourceDatabase - 阅读进度]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SourceDatabase - 删除书架条目级联删除缓存和进度]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SourceDatabase - 删除书架条目级联删除缓存和进度]==])
set_tests_properties( [==[SourceDatabase - 删除书架条目级联删除缓存和进度]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SourceDatabase - 批量查询缓存数量]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SourceDatabase - 批量查询缓存数量]==])
set_tests_properties( [==[SourceDatabase - 批量查询缓存数量]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SourceDatabase - URL 历史记录]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SourceDatabase - URL 历史记录]==])
set_tests_properties( [==[SourceDatabase - URL 历史记录]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[bookshelf: add / is_in / remove / get 工作闭环]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=bookshelf: add / is_in / remove / get 工作闭环]==])
set_tests_properties( [==[bookshelf: add / is_in / remove / get 工作闭环]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[read progress: save / get]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=read progress: save / get]==])
set_tests_properties( [==[read progress: save / get]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[catalog cache: cacheBookCatalog / getCachedCatalog / clearBookCache 闭环]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=catalog cache: cacheBookCatalog / getCachedCatalog / clearBookCache 闭环]==])
set_tests_properties( [==[catalog cache: cacheBookCatalog / getCachedCatalog / clearBookCache 闭环]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[exportBookToTxt: 未在书架 → 空串 + lastError]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=exportBookToTxt: 未在书架 → 空串 + lastError]==])
set_tests_properties( [==[exportBookToTxt: 未在书架 → 空串 + lastError]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[exportBookToTxt: 已入书架但无目录缓存 → 空串 + lastError]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=exportBookToTxt: 已入书架但无目录缓存 → 空串 + lastError]==])
set_tests_properties( [==[exportBookToTxt: 已入书架但无目录缓存 → 空串 + lastError]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[exportBookToTxt: 正常导出（部分章节正文未缓存时也能导出，缺失章节标注）]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=exportBookToTxt: 正常导出（部分章节正文未缓存时也能导出，缺失章节标注）]==])
set_tests_properties( [==[exportBookToTxt: 正常导出（部分章节正文未缓存时也能导出，缺失章节标注）]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[validityToString - 枚举转字符串]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=validityToString - 枚举转字符串]==])
set_tests_properties( [==[validityToString - 枚举转字符串]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[isValidValidity - 有效性判断]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=isValidValidity - 有效性判断]==])
set_tests_properties( [==[isValidValidity - 有效性判断]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[BookSourceEngine - 加载书源]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=BookSourceEngine - 加载书源]==])
set_tests_properties( [==[BookSourceEngine - 加载书源]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[BookSourceEngine - 设置书源有效性]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=BookSourceEngine - 设置书源有效性]==])
set_tests_properties( [==[BookSourceEngine - 设置书源有效性]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[BookSourceEngine - validSourceCount 只统计优和良]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=BookSourceEngine - validSourceCount 只统计优和良]==])
set_tests_properties( [==[BookSourceEngine - validSourceCount 只统计优和良]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[BookSourceEngine - getSourceList 只返回 Unknown/Excellent/Good]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=BookSourceEngine - getSourceList 只返回 Unknown/Excellent/Good]==])
set_tests_properties( [==[BookSourceEngine - getSourceList 只返回 Unknown/Excellent/Good]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[BookSourceEngine - getSourceList 无 searchUrl 的书源不计入]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=BookSourceEngine - getSourceList 无 searchUrl 的书源不计入]==])
set_tests_properties( [==[BookSourceEngine - getSourceList 无 searchUrl 的书源不计入]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[BookSourceEngine - removeInvalidSources 删除差和无效]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=BookSourceEngine - removeInvalidSources 删除差和无效]==])
set_tests_properties( [==[BookSourceEngine - removeInvalidSources 删除差和无效]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[BookSourceEngine - exportGoodSources 只导出优和良]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=BookSourceEngine - exportGoodSources 只导出优和良]==])
set_tests_properties( [==[BookSourceEngine - exportGoodSources 只导出优和良]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[BookSourceEngine - clearAllSources]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=BookSourceEngine - clearAllSources]==])
set_tests_properties( [==[BookSourceEngine - clearAllSources]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[BookSourceEngine - selectSource]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=BookSourceEngine - selectSource]==])
set_tests_properties( [==[BookSourceEngine - selectSource]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[BookSourceEngine - version 不为空]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=BookSourceEngine - version 不为空]==])
set_tests_properties( [==[BookSourceEngine - version 不为空]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[集成测试 - 书源加载、检测、过滤、导出完整流程]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=集成测试 - 书源加载、检测、过滤、导出完整流程]==])
set_tests_properties( [==[集成测试 - 书源加载、检测、过滤、导出完整流程]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[集成测试 - 书源持久化和重启恢复]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=集成测试 - 书源持久化和重启恢复]==])
set_tests_properties( [==[集成测试 - 书源持久化和重启恢复]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[集成测试 - 书架和缓存完整流程]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=集成测试 - 书架和缓存完整流程]==])
set_tests_properties( [==[集成测试 - 书架和缓存完整流程]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[集成测试 - 检测过程中 getSourceList 实时过滤]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=集成测试 - 检测过程中 getSourceList 实时过滤]==])
set_tests_properties( [==[集成测试 - 检测过程中 getSourceList 实时过滤]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[集成测试 - 书源重新检测后恢复到列表]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=集成测试 - 书源重新检测后恢复到列表]==])
set_tests_properties( [==[集成测试 - 书源重新检测后恢复到列表]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[集成测试 - 多本书缓存完全隔离]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=集成测试 - 多本书缓存完全隔离]==])
set_tests_properties( [==[集成测试 - 多本书缓存完全隔离]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[集成测试 - downloadBook 无 sleepMs 参数]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=集成测试 - downloadBook 无 sleepMs 参数]==])
set_tests_properties( [==[集成测试 - downloadBook 无 sleepMs 参数]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[集成测试 - openBookSession 状态快照]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=集成测试 - openBookSession 状态快照]==])
set_tests_properties( [==[集成测试 - openBookSession 状态快照]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[rss: imported boolean and null extras preserve rules after database reload]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=rss: imported boolean and null extras preserve rules after database reload]==])
set_tests_properties( [==[rss: imported boolean and null extras preserve rules after database reload]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[rss: fast raw fragments without valid articles are never healthy]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=rss: fast raw fragments without valid articles are never healthy]==])
set_tests_properties( [==[rss: fast raw fragments without valid articles are never healthy]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[rss: list and content requests preserve POST bodies headers and URL options]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=rss: list and content requests preserve POST bodies headers and URL options]==])
set_tests_properties( [==[rss: list and content requests preserve POST bodies headers and URL options]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[rss: content AJAX uses source headers and isolated JavaScript state]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=rss: content AJAX uses source headers and isolated JavaScript state]==])
set_tests_properties( [==[rss: content AJAX uses source headers and isolated JavaScript state]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[rss: feed CDATA and Atom alternate links resolve against redirected feed URL]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=rss: feed CDATA and Atom alternate links resolve against redirected feed URL]==])
set_tests_properties( [==[rss: feed CDATA and Atom alternate links resolve against redirected feed URL]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[rss: inline feed content remains readable when original is unavailable]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=rss: inline feed content remains readable when original is unavailable]==])
set_tests_properties( [==[rss: inline feed content remains readable when original is unavailable]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[rss: unreadable content is diagnosed and failed refresh keeps cached articles]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=rss: unreadable content is diagnosed and failed refresh keeps cached articles]==])
set_tests_properties( [==[rss: unreadable content is diagnosed and failed refresh keeps cached articles]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[rss: URL import accepts JSON instead of requiring feed markers]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=rss: URL import accepts JSON instead of requiring feed markers]==])
set_tests_properties( [==[rss: URL import accepts JSON instead of requiring feed markers]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[rss: JavaScript channels arrays and persistent source variables]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=rss: JavaScript channels arrays and persistent source variables]==])
set_tests_properties( [==[rss: JavaScript channels arrays and persistent source variables]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[rss: content rule failure preserves readable fallback but not a healthy rating]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=rss: content rule failure preserves readable fallback but not a healthy rating]==])
set_tests_properties( [==[rss: content rule failure preserves readable fallback but not a healthy rating]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[rss: checking content has the same isolated state as the reader]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=rss: checking content has the same isolated state as the reader]==])
set_tests_properties( [==[rss: checking content has the same isolated state as the reader]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[rss: lazy images are normalized and empty image URLs are not readable]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=rss: lazy images are normalized and empty image URLs are not readable]==])
set_tests_properties( [==[rss: lazy images are normalized and empty image URLs are not readable]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[rss: image-only rule articles retain their visible content]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=rss: image-only rule articles retain their visible content]==])
set_tests_properties( [==[rss: image-only rule articles retain their visible content]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[rss: public articles remain readable beside login widgets]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=rss: public articles remain readable beside login widgets]==])
set_tests_properties( [==[rss: public articles remain readable beside login widgets]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[rss: portable list loading fetches empty cache despite imported timestamp]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=rss: portable list loading fetches empty cache despite imported timestamp]==])
set_tests_properties( [==[rss: portable list loading fetches empty cache despite imported timestamp]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[normalizeText - 基本归一化]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=normalizeText - 基本归一化]==])
set_tests_properties( [==[normalizeText - 基本归一化]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[bookMatchScore - 只勾选书名]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=bookMatchScore - 只勾选书名]==])
set_tests_properties( [==[bookMatchScore - 只勾选书名]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[bookMatchScore - 只勾选作者]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=bookMatchScore - 只勾选作者]==])
set_tests_properties( [==[bookMatchScore - 只勾选作者]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[bookMatchScore - 同时勾选书名+作者（或关系）]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=bookMatchScore - 同时勾选书名+作者（或关系）]==])
set_tests_properties( [==[bookMatchScore - 同时勾选书名+作者（或关系）]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[bookMatchScore - 勾选简介]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=bookMatchScore - 勾选简介]==])
set_tests_properties( [==[bookMatchScore - 勾选简介]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[bookMatchScore - 全部不勾选 → 不过滤]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=bookMatchScore - 全部不勾选 → 不过滤]==])
set_tests_properties( [==[bookMatchScore - 全部不勾选 → 不过滤]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[bookMatchScore - 空关键词]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=bookMatchScore - 空关键词]==])
set_tests_properties( [==[bookMatchScore - 空关键词]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( isBlank /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=isBlank]==])
set_tests_properties( isBlank PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[decodeHtmlEntities - 命名实体]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=decodeHtmlEntities - 命名实体]==])
set_tests_properties( [==[decodeHtmlEntities - 命名实体]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[decodeHtmlEntities - 数字实体]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=decodeHtmlEntities - 数字实体]==])
set_tests_properties( [==[decodeHtmlEntities - 数字实体]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[decodeHtmlEntities - 混合文本]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=decodeHtmlEntities - 混合文本]==])
set_tests_properties( [==[decodeHtmlEntities - 混合文本]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[decodeHtmlEntities - 无实体]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=decodeHtmlEntities - 无实体]==])
set_tests_properties( [==[decodeHtmlEntities - 无实体]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[stripCdata - 基本剥离]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=stripCdata - 基本剥离]==])
set_tests_properties( [==[stripCdata - 基本剥离]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[stripCdata - 无 CDATA 原样返回]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=stripCdata - 无 CDATA 原样返回]==])
set_tests_properties( [==[stripCdata - 无 CDATA 原样返回]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[stripCdata - 前后混合文本与多段]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=stripCdata - 前后混合文本与多段]==])
set_tests_properties( [==[stripCdata - 前后混合文本与多段]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[stripCdata - 未闭合容错]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=stripCdata - 未闭合容错]==])
set_tests_properties( [==[stripCdata - 未闭合容错]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[decodeHtmlEntities - 自动剥离 CDATA 后再解码]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=decodeHtmlEntities - 自动剥离 CDATA 后再解码]==])
set_tests_properties( [==[decodeHtmlEntities - 自动剥离 CDATA 后再解码]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[cleanContent - 基本清理]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=cleanContent - 基本清理]==])
set_tests_properties( [==[cleanContent - 基本清理]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[cleanContent - 复杂 HTML]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=cleanContent - 复杂 HTML]==])
set_tests_properties( [==[cleanContent - 复杂 HTML]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( isValidUtf8 /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=isValidUtf8]==])
set_tests_properties( isValidUtf8 PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( sanitizeUtf8 /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=sanitizeUtf8]==])
set_tests_properties( sanitizeUtf8 PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( trimCopy /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=trimCopy]==])
set_tests_properties( trimCopy PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[getAbsoluteURL - 协议相对 // 继承 scheme，不重复 host]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=getAbsoluteURL - 协议相对 // 继承 scheme，不重复 host]==])
set_tests_properties( [==[getAbsoluteURL - 协议相对 // 继承 scheme，不重复 host]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[getAbsoluteURL - 绝对路径 /]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=getAbsoluteURL - 绝对路径 /]==])
set_tests_properties( [==[getAbsoluteURL - 绝对路径 /]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[getAbsoluteURL - 书源作者标记和查询参数不属于主机或路径]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=getAbsoluteURL - 书源作者标记和查询参数不属于主机或路径]==])
set_tests_properties( [==[getAbsoluteURL - 书源作者标记和查询参数不属于主机或路径]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[getAbsoluteURL - 查询与锚点单独解析且不规范化参数内容]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=getAbsoluteURL - 查询与锚点单独解析且不规范化参数内容]==])
set_tests_properties( [==[getAbsoluteURL - 查询与锚点单独解析且不规范化参数内容]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[getAbsoluteURL - 相对路径与 ../]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=getAbsoluteURL - 相对路径与 ../]==])
set_tests_properties( [==[getAbsoluteURL - 相对路径与 ../]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[getAbsoluteURL - 已是绝对/特殊 URL 原样]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=getAbsoluteURL - 已是绝对/特殊 URL 原样]==])
set_tests_properties( [==[getAbsoluteURL - 已是绝对/特殊 URL 原样]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[validate_sources_concurrent - 空列表立刻完成]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=validate_sources_concurrent - 空列表立刻完成]==])
set_tests_properties( [==[validate_sources_concurrent - 空列表立刻完成]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[setValidateMaxTaskSec - 边界值合法化]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=setValidateMaxTaskSec - 边界值合法化]==])
set_tests_properties( [==[setValidateMaxTaskSec - 边界值合法化]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[validate 所有 Invalid 源：无网络情况下能在超时兜底内完成]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=validate 所有 Invalid 源：无网络情况下能在超时兜底内完成]==])
set_tests_properties( [==[validate 所有 Invalid 源：无网络情况下能在超时兜底内完成]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[rating - 一切顺利：1 本通过 → Excellent，路径耗时 = search + 单本 verify]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=rating - 一切顺利：1 本通过 → Excellent，路径耗时 = search + 单本 verify]==])
set_tests_properties( [==[rating - 一切顺利：1 本通过 → Excellent，路径耗时 = search + 单本 verify]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[rating - 失败分支不计入：前 4 本 catalog 报错，第 5 本秒过 → 评级用第 5 本耗时]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=rating - 失败分支不计入：前 4 本 catalog 报错，第 5 本秒过 → 评级用第 5 本耗时]==])
set_tests_properties( [==[rating - 失败分支不计入：前 4 本 catalog 报错，第 5 本秒过 → 评级用第 5 本耗时]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[rating - 9000ms 兜底：成功但太慢 → Invalid]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=rating - 9000ms 兜底：成功但太慢 → Invalid]==])
set_tests_properties( [==[rating - 9000ms 兜底：成功但太慢 → Invalid]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[rating - 全部 5 本 catalog 都失败 → Invalid: no book passed]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=rating - 全部 5 本 catalog 都失败 → Invalid: no book passed]==])
set_tests_properties( [==[rating - 全部 5 本 catalog 都失败 → Invalid: no book passed]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[rating - 搜索 0 结果 → Invalid: no search results]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=rating - 搜索 0 结果 → Invalid: no search results]==])
set_tests_properties( [==[rating - 搜索 0 结果 → Invalid: no search results]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[rating - 搜索全部失败 → Invalid: no response from server]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=rating - 搜索全部失败 → Invalid: no response from server]==])
set_tests_properties( [==[rating - 搜索全部失败 → Invalid: no response from server]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[rating - 章节数不足（< 3） → 视为无目录 → Invalid]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=rating - 章节数不足（< 3） → 视为无目录 → Invalid]==])
set_tests_properties( [==[rating - 章节数不足（< 3） → 视为无目录 → Invalid]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[rating - 正文太短（< 50 字节） → Invalid]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=rating - 正文太短（< 50 字节） → Invalid]==])
set_tests_properties( [==[rating - 正文太短（< 50 字节） → Invalid]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[JsonPathSelector - basic]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=JsonPathSelector - basic]==])
set_tests_properties( [==[JsonPathSelector - basic]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[JsonPathSelector - nested]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=JsonPathSelector - nested]==])
set_tests_properties( [==[JsonPathSelector - nested]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[RegexSelector - basic]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=RegexSelector - basic]==])
set_tests_properties( [==[RegexSelector - basic]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SelectorFactory - detectType]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SelectorFactory - detectType]==])
set_tests_properties( [==[SelectorFactory - detectType]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SelectorFactory - create]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SelectorFactory - create]==])
set_tests_properties( [==[SelectorFactory - create]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[applyRuleStatic - chain @js: selector@js:code]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=applyRuleStatic - chain @js: selector@js:code]==])
set_tests_properties( [==[applyRuleStatic - chain @js: selector@js:code]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[applyRuleStatic - chain <js> selector<js>code</js>]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=applyRuleStatic - chain <js> selector<js>code</js>]==])
set_tests_properties( [==[applyRuleStatic - chain <js> selector<js>code</js>]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[applyRuleStatic - pure @js: (not chain)]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=applyRuleStatic - pure @js: (not chain)]==])
set_tests_properties( [==[applyRuleStatic - pure @js: (not chain)]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[applyRuleStatic - no JS, pure selector]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=applyRuleStatic - no JS\, pure selector]==])
set_tests_properties( [==[applyRuleStatic - no JS, pure selector]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[applyRuleStatic - JSONPath rule not affected by chain JS detection]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=applyRuleStatic - JSONPath rule not affected by chain JS detection]==])
set_tests_properties( [==[applyRuleStatic - JSONPath rule not affected by chain JS detection]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SourceParser - parse single source]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SourceParser - parse single source]==])
set_tests_properties( [==[SourceParser - parse single source]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SourceParser - validate]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SourceParser - validate]==])
set_tests_properties( [==[SourceParser - validate]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SourceParser - parse array]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SourceParser - parse array]==])
set_tests_properties( [==[SourceParser - parse array]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
add_test( [==[SourceParser - serialize]==] /Users/conycqzhang/Learning/Work/OpenRead/build-asan/bin/openread-tests [==[--test-case=SourceParser - serialize]==])
set_tests_properties( [==[SourceParser - serialize]==] PROPERTIES WORKING_DIRECTORY /Users/conycqzhang/Learning/Work/OpenRead/build-asan/tests TIMEOUT 60 LABELS)
set( openread-tests_TESTS [==[DebugConsole - 输出日志结果与隔离状态]==] [==[DebugConsole - 错误超时与输入限制]==] [==[DebugConsole - 输出上限与 UTF8 边界]==] [==[DebugConsole - 异常输出上限与 UTF8 边界]==] [==[SourceDebug - 搜索目录正文及 HTTP 事件]==] [==[SourceDebug - 空搜索结果报告阶段失败]==] [==[SourceDebug - 断连后不再发起请求]==] [==[SourceDebug - 多项慢规则共享整体时间预算]==] [==[SourceDebug - JS 执行中断连立即取消且不再发起 HTTP]==] [==[SourceDebug - JS HTTP 桥接不能吞掉请求上限错误]==] [==[SourceDebug - 引擎取消检查清空后可重新使用]==] [==[SourceDebug - 指定书源读取取消后恢复原先选择]==] [==[SourceDebug - RSS 读取取消后移除临时书源并恢复选择]==] [==[SourceDebug - JS HTTP 桥接不能吞掉一次性取消检查异常]==] [==[StartupOptions - 默认值和帮助]==] [==[StartupOptions - 命名参数互不干扰]==] [==[StartupOptions - 兼容位置参数及混合参数]==] [==[StartupOptions - 拒绝无效端口及参数]==] [==[JsRuntime - 死循环超时后仍可复用]==] [==[JsRuntime - 规则超时不会回退原文且错误不污染后续执行]==] [==[JsRuntime - 结果转换期间同样受超时约束]==] [==[JsRuntime - 序列化异常被报告和消费且不会回退原文]==] [==[JsRuntime - 读取序列化函数异常保留原始错误]==] [==[JsRuntime - 异常格式化再次异常或超时均被消费]==] [==[JsRuntime - 执行前中断不执行脚本且清除回调后可复用]==] [==[JsRuntime - 执行中中断不会被脚本捕获吞掉]==] [==[JsRuntime - 中断回调抛出的异常不会跨越 QuickJS 边界]==] [==[JsRuntime - 序列化时同样响应中断且错误不污染后续执行]==] [==[JsRuntime - 拒绝非正数超时]==] [==[CssEngine - 基础类型/class/id 选择]==] [==[CssEngine - 组合器]==] [==[CssEngine - 属性选择器]==] [==[CssEngine - 伪类]==] [==[CssSelector - @CSS: 规则取值]==] [==[XPathEngine - 路径与属性]==] [==[SelectorFactory - 新引擎可创建并工作]==] [==[JsRuntime - @put/@get 变量表]==] [==[JsRuntime - java.ajax 经 HttpFunc 真实回调]==] [==[applyRuleStatic - @put 写入 + @get 读取]==] [==[DefaultJSoup - CSS 兜底处理复杂选择器]==] [==[applyRuleStatic - && 为合并而非管道]==] [==[applyRuleStatic - 模板内嵌 {{选择器&&选择器}} 多结果 join]==] [==[SourceDatabase - 书源插入和查询]==] [==[SourceDatabase - validity 持久化到数据库]==] [==[SourceDatabase - removeInvalidSources 删除差和无效]==] [==[SourceDatabase - 书架操作]==] [==[SourceDatabase - 目录缓存]==] [==[SourceDatabase - 正文缓存]==] [==[SourceDatabase - 阅读进度]==] [==[SourceDatabase - 删除书架条目级联删除缓存和进度]==] [==[SourceDatabase - 批量查询缓存数量]==] [==[SourceDatabase - URL 历史记录]==] [==[bookshelf: add / is_in / remove / get 工作闭环]==] [==[read progress: save / get]==] [==[catalog cache: cacheBookCatalog / getCachedCatalog / clearBookCache 闭环]==] [==[exportBookToTxt: 未在书架 → 空串 + lastError]==] [==[exportBookToTxt: 已入书架但无目录缓存 → 空串 + lastError]==] [==[exportBookToTxt: 正常导出（部分章节正文未缓存时也能导出，缺失章节标注）]==] [==[validityToString - 枚举转字符串]==] [==[isValidValidity - 有效性判断]==] [==[BookSourceEngine - 加载书源]==] [==[BookSourceEngine - 设置书源有效性]==] [==[BookSourceEngine - validSourceCount 只统计优和良]==] [==[BookSourceEngine - getSourceList 只返回 Unknown/Excellent/Good]==] [==[BookSourceEngine - getSourceList 无 searchUrl 的书源不计入]==] [==[BookSourceEngine - removeInvalidSources 删除差和无效]==] [==[BookSourceEngine - exportGoodSources 只导出优和良]==] [==[BookSourceEngine - clearAllSources]==] [==[BookSourceEngine - selectSource]==] [==[BookSourceEngine - version 不为空]==] [==[集成测试 - 书源加载、检测、过滤、导出完整流程]==] [==[集成测试 - 书源持久化和重启恢复]==] [==[集成测试 - 书架和缓存完整流程]==] [==[集成测试 - 检测过程中 getSourceList 实时过滤]==] [==[集成测试 - 书源重新检测后恢复到列表]==] [==[集成测试 - 多本书缓存完全隔离]==] [==[集成测试 - downloadBook 无 sleepMs 参数]==] [==[集成测试 - openBookSession 状态快照]==] [==[rss: imported boolean and null extras preserve rules after database reload]==] [==[rss: fast raw fragments without valid articles are never healthy]==] [==[rss: list and content requests preserve POST bodies headers and URL options]==] [==[rss: content AJAX uses source headers and isolated JavaScript state]==] [==[rss: feed CDATA and Atom alternate links resolve against redirected feed URL]==] [==[rss: inline feed content remains readable when original is unavailable]==] [==[rss: unreadable content is diagnosed and failed refresh keeps cached articles]==] [==[rss: URL import accepts JSON instead of requiring feed markers]==] [==[rss: JavaScript channels arrays and persistent source variables]==] [==[rss: content rule failure preserves readable fallback but not a healthy rating]==] [==[rss: checking content has the same isolated state as the reader]==] [==[rss: lazy images are normalized and empty image URLs are not readable]==] [==[rss: image-only rule articles retain their visible content]==] [==[rss: public articles remain readable beside login widgets]==] [==[rss: portable list loading fetches empty cache despite imported timestamp]==] [==[normalizeText - 基本归一化]==] [==[bookMatchScore - 只勾选书名]==] [==[bookMatchScore - 只勾选作者]==] [==[bookMatchScore - 同时勾选书名+作者（或关系）]==] [==[bookMatchScore - 勾选简介]==] [==[bookMatchScore - 全部不勾选 → 不过滤]==] [==[bookMatchScore - 空关键词]==] isBlank [==[decodeHtmlEntities - 命名实体]==] [==[decodeHtmlEntities - 数字实体]==] [==[decodeHtmlEntities - 混合文本]==] [==[decodeHtmlEntities - 无实体]==] [==[stripCdata - 基本剥离]==] [==[stripCdata - 无 CDATA 原样返回]==] [==[stripCdata - 前后混合文本与多段]==] [==[stripCdata - 未闭合容错]==] [==[decodeHtmlEntities - 自动剥离 CDATA 后再解码]==] [==[cleanContent - 基本清理]==] [==[cleanContent - 复杂 HTML]==] isValidUtf8 sanitizeUtf8 trimCopy [==[getAbsoluteURL - 协议相对 // 继承 scheme，不重复 host]==] [==[getAbsoluteURL - 绝对路径 /]==] [==[getAbsoluteURL - 书源作者标记和查询参数不属于主机或路径]==] [==[getAbsoluteURL - 查询与锚点单独解析且不规范化参数内容]==] [==[getAbsoluteURL - 相对路径与 ../]==] [==[getAbsoluteURL - 已是绝对/特殊 URL 原样]==] [==[validate_sources_concurrent - 空列表立刻完成]==] [==[setValidateMaxTaskSec - 边界值合法化]==] [==[validate 所有 Invalid 源：无网络情况下能在超时兜底内完成]==] [==[rating - 一切顺利：1 本通过 → Excellent，路径耗时 = search + 单本 verify]==] [==[rating - 失败分支不计入：前 4 本 catalog 报错，第 5 本秒过 → 评级用第 5 本耗时]==] [==[rating - 9000ms 兜底：成功但太慢 → Invalid]==] [==[rating - 全部 5 本 catalog 都失败 → Invalid: no book passed]==] [==[rating - 搜索 0 结果 → Invalid: no search results]==] [==[rating - 搜索全部失败 → Invalid: no response from server]==] [==[rating - 章节数不足（< 3） → 视为无目录 → Invalid]==] [==[rating - 正文太短（< 50 字节） → Invalid]==] [==[JsonPathSelector - basic]==] [==[JsonPathSelector - nested]==] [==[RegexSelector - basic]==] [==[SelectorFactory - detectType]==] [==[SelectorFactory - create]==] [==[applyRuleStatic - chain @js: selector@js:code]==] [==[applyRuleStatic - chain <js> selector<js>code</js>]==] [==[applyRuleStatic - pure @js: (not chain)]==] [==[applyRuleStatic - no JS, pure selector]==] [==[applyRuleStatic - JSONPath rule not affected by chain JS detection]==] [==[SourceParser - parse single source]==] [==[SourceParser - validate]==] [==[SourceParser - parse array]==] [==[SourceParser - serialize]==])
