/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2025 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: darwin64-arm64-cc"
#define DATE "built on: Mon Sep 14 07:25:26 2026 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','c','c',' ','-','f','P',
    'I','C',' ','-','a','r','c','h',' ','a','r','m','6','4',' ','-',
    'W','n','o','-','i','m','p','l','i','c','i','t','-','i','n','t',
    ' ','-','W','n','o','-','i','n','c','o','m','p','a','t','i','b',
    'l','e','-','p','o','i','n','t','e','r','-','t','y','p','e','s',
    ' ','-','W','n','o','-','i','n','t','-','c','o','n','v','e','r',
    's','i','o','n',' ','-','W','n','o','-','d','e','p','r','e','c',
    'a','t','e','d','-','n','o','n','-','p','r','o','t','o','t','y',
    'p','e',' ','-','D','L','_','E','N','D','I','A','N',' ','-','D',
    'O','P','E','N','S','S','L','_','P','I','C',' ','-','D','_','R',
    'E','E','N','T','R','A','N','T',' ','-','D','N','D','E','B','U',
    'G','\0'
};
